<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CBA7UQ0" ignored="2" name="Default test(failed)" tests="1" failures="1" timestamp="2020-12-08T22:45:47 IST" time="0.107" errors="0">
  <testcase name="TC3" time="0.02" classname="failedTC.ExcuteFailedTC">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:55)
at junit.framework.Assert.fail(Assert.java:64)
at failedTC.ExcuteFailedTC.TC3(ExcuteFailedTC.java:24)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TC3 -->
  <testcase name="TC2" time="0.0" classname="failedTC.ExcuteFailedTC">
    <ignored/>
  </testcase> <!-- TC2 -->
  <testcase name="TC1" time="0.0" classname="failedTC.ExcuteFailedTC">
    <ignored/>
  </testcase> <!-- TC1 -->
</testsuite> <!-- Default test(failed) -->
